/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Medico;
import Classes.PacienteConsulta;
import DAO.PacienteConsultaDAO;
import DAO.PacienteDAO;
import Classes.Paciente;
import DAO.MedicoDAO;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yugurimaru
 */
public class Consultas_procurar_paciente extends javax.swing.JFrame {

    ArrayList<PacienteConsulta> PacienteConsulta = new ArrayList();
    ArrayList<Paciente> paciente = new ArrayList();
    
    /**
     * Creates new form Consultas_procurar_data
     */
    public Consultas_procurar_paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BT_atualizar = new javax.swing.JButton();
        CB_id_paciente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas por Paciente");
        setPreferredSize(new java.awt.Dimension(1070, 456));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Consulta", "Nome Médico", "Nome Paciente", "Data Consulta", "Hora Consulta", "Compareceu", "Sexo", "Data Nascimento", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jLabel1.setText("Selecione o Paciente");

        BT_atualizar.setText("Atualizar");
        BT_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_atualizarMousePressed(evt);
            }
        });

        CB_id_paciente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_id_pacienteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_id_paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BT_atualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_id_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BT_atualizar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void BT_atualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_atualizarMousePressed
        Atualizar_tabela();
    }//GEN-LAST:event_BT_atualizarMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            CB_id_paciente.removeAllItems();

            PacienteDAO PDAO = new PacienteDAO();
            paciente = PDAO.Listar();

        } catch (Exception e) {
            System.out.println("problema");
        }
        for (int i = 0; i < paciente.size(); i++) {
            CB_id_paciente.addItem(paciente.get(i).getNome_pac());
        }
    }//GEN-LAST:event_formWindowOpened

    private void CB_id_pacienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_id_pacienteItemStateChanged
        Atualizar_tabela();
    }//GEN-LAST:event_CB_id_pacienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    private void Atualizar_tabela() {

        DefaultTableModel table = (DefaultTableModel) Tabela.getModel();
        Tabela.removeAll();
        String id_medico, id_paciente, id_consulta, data_string, hora_string, compareceu, nome, sexo, data_nascimento, telefone;
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");

        if (Tabela.getRowCount() > 0) {
            while (Tabela.getRowCount() > 0) {
                table.removeRow(0);
            }
        }

        PacienteConsultaDAO PCDAO;
        try {
            PCDAO = new PacienteConsultaDAO();
            
            //Seleciona o paciente da ComboBox
            Paciente paciente_selecionado = paciente.get(CB_id_paciente.getSelectedIndex());
            int codigo_paciente = paciente_selecionado.getCodigo();
            
            PacienteConsulta = PCDAO.ListarConsulta(codigo_paciente);
        } catch (NumberFormatException e) {
            System.out.println("Erro de conexão ao banco.");
        }

        for (int i = 0; i < PacienteConsulta.size(); i++) {
            int id_medico_procurar = PacienteConsulta.get(i).getId_medico();
            MedicoDAO MDAO = new MedicoDAO();
            Medico medico = MDAO.Procurar(id_medico_procurar);
            id_medico = medico.getNome_med();
            
            int id_paciente_procurar = PacienteConsulta.get(i).getId_paciente();
            PacienteDAO PDAO = new PacienteDAO();
            Paciente paciente = PDAO.procurar(id_paciente_procurar);
            id_paciente = paciente.getNome_pac();
            
            
            id_consulta = Integer.toString(PacienteConsulta.get(i).getId_consulta());

            data_string = dtOutput.format(PacienteConsulta.get(i).getData());

            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
            Time hora;

            try {
                hora = PacienteConsulta.get(i).getHora();
                hora_string = format.format(hora);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro na conversão da hora");
                hora_string = null;
            }

            compareceu = PacienteConsulta.get(i).getCompareceu() + "";
            
            nome = PacienteConsulta.get(i).getNome_pac();
            sexo = PacienteConsulta.get(i).getSexo() + " ";
            data_nascimento = dtOutput.format(PacienteConsulta.get(i).getData_pac());
            telefone = PacienteConsulta.get(i).getFone();
            

            table.addRow(new String[]{id_consulta, id_medico, id_paciente, data_string, hora_string, compareceu, nome, sexo, data_nascimento, telefone, });
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_atualizar;
    private javax.swing.JComboBox<String> CB_id_paciente;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
