/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Consulta;
import DAO.ConsultaDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author yugurimaru
 */
public class Consultas_procurar extends javax.swing.JFrame {

    ArrayList<Consulta> consulta_arraylist = new ArrayList();
    
    /**
     * Creates new form Pacientes_procurar
     */
    public Consultas_procurar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_id_medico = new javax.swing.JTextField();
        RB_nao = new javax.swing.JRadioButton();
        RB_sim = new javax.swing.JRadioButton();
        TF_hora_consulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TF_id_paciente = new javax.swing.JTextField();
        RB_aberto = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        DC_data_consulta = new datechooser.beans.DateChooserPanel();
        CB_procurar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Informe o ID da consulta:");

        jLabel2.setText("ID Médico:");

        jLabel3.setText("Data Consulta:");

        jLabel4.setText("Compareceu:");

        TF_id_medico.setEditable(false);

        buttonGroup1.add(RB_nao);
        RB_nao.setText("Não");

        buttonGroup1.add(RB_sim);
        RB_sim.setText("Sim");
        RB_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_simActionPerformed(evt);
            }
        });

        TF_hora_consulta.setEditable(false);

        jLabel6.setText("ID Paciente:");

        TF_id_paciente.setEditable(false);

        buttonGroup1.add(RB_aberto);
        RB_aberto.setText("Em aberto");

        jLabel7.setText("Hora Consulta:");

        DC_data_consulta.setLocked(true);

        CB_procurar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_procurarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DC_data_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_hora_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TF_id_medico)
                                .addComponent(TF_id_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(RB_nao)
                .addGap(18, 18, 18)
                .addComponent(RB_aberto)
                .addGap(18, 18, 18)
                .addComponent(RB_sim)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_id_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_id_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RB_nao)
                    .addComponent(RB_sim)
                    .addComponent(RB_aberto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_hora_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DC_data_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConsultaDAO CDAO = new ConsultaDAO();
        try {
            CB_procurar.removeAllItems();
            consulta_arraylist = CDAO.Listar();

        } catch (Exception e) {
            System.out.println("problema");
        }

        for (int i = 0; i < consulta_arraylist.size(); i++) {
            CB_procurar.addItem(String.valueOf(consulta_arraylist.get(i).getId_consulta()));
        }
        RB_nao.setEnabled(false);
        RB_sim.setEnabled(false);
        RB_aberto.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void RB_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_simActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_simActionPerformed

    private void CB_procurarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_procurarItemStateChanged
        ConsultaDAO CDAO = new ConsultaDAO();
        try {

            Consulta consulta_selecionado = consulta_arraylist.get(CB_procurar.getSelectedIndex());
            String id_paciente = String.valueOf(consulta_selecionado.getId_consulta());
            int id_consulta_int = Integer.parseInt(id_paciente);
            
            Consulta consulta = CDAO.Procurar(id_consulta_int);

            if (consulta != null) {
                String hora_string;
                
                TF_id_medico.setText(String.valueOf(consulta.getId_medico()));
                TF_id_paciente.setText(String.valueOf(consulta.getId_paciente()));

                Calendar calendar = Calendar.getInstance();
                calendar.setTime(consulta.getData());
                DC_data_consulta.setSelectedDate(calendar);

                SimpleDateFormat format = new SimpleDateFormat("HH:mm");
                hora_string = format.format(consulta.getHora());
                TF_hora_consulta.setText(hora_string);


                if (consulta.getCompareceu() == 'N' || consulta.getCompareceu() == 'n') {
                    RB_nao.setSelected(true);
                    RB_sim.setSelected(false);
                    RB_aberto.setSelected(false);
                } else if (consulta.getCompareceu() == 'S' || consulta.getCompareceu() == 's') {
                    RB_nao.setSelected(false);
                    RB_sim.setSelected(true);
                    RB_aberto.setSelected(false);
                } else {
                    RB_nao.setSelected(false);
                    RB_sim.setSelected(false);
                    RB_aberto.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Consulta não encontrada.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Entrada inválida. Certifique-se de que seja um número inteiro.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Problema ao procurar Consulta");
        }
    }//GEN-LAST:event_CB_procurarItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_procurar;
    private datechooser.beans.DateChooserPanel DC_data_consulta;
    private javax.swing.JRadioButton RB_aberto;
    private javax.swing.JRadioButton RB_nao;
    private javax.swing.JRadioButton RB_sim;
    private javax.swing.JTextField TF_hora_consulta;
    private javax.swing.JTextField TF_id_medico;
    private javax.swing.JTextField TF_id_paciente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
