/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DAO.ErpDAOException;
import Classes.Consulta;
import DAO.ConsultaDAO;
import Classes.Medico;
import DAO.MedicoDAO;
import Classes.Paciente;
import DAO.PacienteDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author yugurimaru
 */
public class Consultas_inserir extends javax.swing.JFrame {
    
    
    ArrayList<Medico> medico = new ArrayList();
    ArrayList<Paciente> paciente = new ArrayList();

    /**
     * Creates new form Pacientes_Inserir
     */
    public Consultas_inserir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BT_Salvar = new javax.swing.JButton();
        BT_Cancelar = new javax.swing.JButton();
        RB_nao = new javax.swing.JRadioButton();
        RB_sim = new javax.swing.JRadioButton();
        RB_aberto = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        TF_hora_consulta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DC_data_consulta = new datechooser.beans.DateChooserPanel();
        CB_id_medico = new javax.swing.JComboBox<>();
        CB_id_paciente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Consultas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Compareceu:");

        jLabel4.setText("Data da Consulta:");

        BT_Salvar.setText("Salvar");
        BT_Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_SalvarMousePressed(evt);
            }
        });

        BT_Cancelar.setText("Cancelar");
        BT_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_nao);
        RB_nao.setText("Não");
        RB_nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_naoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_sim);
        RB_sim.setText("Sim");

        buttonGroup1.add(RB_aberto);
        RB_aberto.setText("Em aberto");

        jLabel1.setText("Hora(HH:mm):");

        jLabel2.setText("Médico:");

        jLabel5.setText("Paciente:");

        CB_id_medico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_id_medicoItemStateChanged(evt);
            }
        });

        CB_id_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_id_pacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CB_id_medico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CB_id_paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(DC_data_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel4)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TF_hora_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_nao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RB_aberto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RB_sim)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(BT_Cancelar)
                        .addGap(54, 54, 54)
                        .addComponent(BT_Salvar)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CB_id_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CB_id_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(DC_data_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_hora_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RB_nao)
                    .addComponent(RB_sim)
                    .addComponent(RB_aberto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Salvar)
                    .addComponent(BT_Cancelar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_CancelarActionPerformed

    private void BT_SalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_SalvarMousePressed
        Consulta C = new Consulta();
        String id_medico, id_paciente, data_string;
        Date dataNasc = null;
        Time hora = null;
        char compareceu = ' ';
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        
        //Seleciona o paciente e o medico da ComboBox
        Medico medico_selecionado = medico.get(CB_id_medico.getSelectedIndex());
        Paciente paciente_selecionado = paciente.get(CB_id_paciente.getSelectedIndex());

        
        if (medico_selecionado == null){
            JOptionPane.showMessageDialog(rootPane, "Selecione o Médico");
        } else if (paciente_selecionado == null){
            JOptionPane.showMessageDialog(rootPane, "Selecione o Paciente");
        } else if ((RB_nao.isSelected() == false) && (RB_sim.isSelected() == false) && RB_aberto.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Compareceu");
        } else {

            id_medico = String.valueOf(medico_selecionado.getID_Medico());
            id_paciente = String.valueOf(paciente_selecionado.getCodigo());

            if (RB_sim.isSelected() == true) {
                compareceu = 'S';
            }
            if (RB_nao.isSelected() == true) {
                compareceu = 'N';
            }
            if (RB_aberto.isSelected() == true) {
                compareceu = 'A';
            }

            Calendar date = DC_data_consulta.getSelectedDate();
            int mes = (int) date.get(Calendar.MONTH);
            mes += 1;
            data_string = (date.get(Calendar.DAY_OF_MONTH) + "/" + mes + "/" + date.get(Calendar.YEAR));
            if (data_string.equals("")) {
                dataNasc = null;

            } else {
                try {
                    dataNasc = dtOutput.parse(data_string);
                } catch (ParseException ex) {
                    System.out.println("Erro na conversão da data");
                }
            }

            if (TF_hora_consulta.getText().equals("")) {
                hora = null;
            } else {
                try {
                    hora = Time.valueOf(TF_hora_consulta.getText() + ":00");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Erro na conversão da hora");
                }
            }

            int id_paciente_int = Integer.parseInt(id_paciente);
            int id_medico_int = Integer.parseInt(id_medico);

            C.setId_paciente(id_paciente_int);
            C.setId_medico(id_medico_int);
            C.setData(dataNasc);
            C.setHora(hora);
            C.setCompareceu(compareceu);

            try {
                ConsultaDAO CDAO = new ConsultaDAO();
                CDAO.Inserir(C);
                JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Problema na inserção da Consulta");
            }
            dispose();
        }


    }//GEN-LAST:event_BT_SalvarMousePressed

    private void RB_naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_naoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_naoActionPerformed

    private void CB_id_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_id_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_id_pacienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Carrega ComboBox
        try {
            CB_id_medico.removeAllItems();
            CB_id_paciente.removeAllItems();
            
            MedicoDAO MDAO = new MedicoDAO();
            medico = MDAO.Listar();
            
            PacienteDAO PDAO = new PacienteDAO();
            paciente = PDAO.Listar();
            
        } catch (Exception e) {
            System.out.println("problema");
        }

        for (int i = 0; i < medico.size(); i++) {
            CB_id_medico.addItem(medico.get(i).getNome_med());

        }
        for (int i = 0; i < paciente.size(); i++) {
            CB_id_paciente.addItem(paciente.get(i).getNome_pac());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void CB_id_medicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_id_medicoItemStateChanged

    }//GEN-LAST:event_CB_id_medicoItemStateChanged

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_Salvar;
    private javax.swing.JComboBox<String> CB_id_medico;
    private javax.swing.JComboBox<String> CB_id_paciente;
    private datechooser.beans.DateChooserPanel DC_data_consulta;
    private javax.swing.JRadioButton RB_aberto;
    private javax.swing.JRadioButton RB_nao;
    private javax.swing.JRadioButton RB_sim;
    private javax.swing.JTextField TF_hora_consulta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
