/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * 
 * 
 * @author yugurimaru
 *
 * 
 * 
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MI_sair = new javax.swing.JMenuItem();
        Menu_Pacientes = new javax.swing.JMenu();
        Menu_medicos = new javax.swing.JMenu();
        MC = new javax.swing.JMenu();
        MConf = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultório");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jMenu3.setText("Menu");

        MI_sair.setText("Sair");
        MI_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MI_sairMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MI_sairMouseReleased(evt);
            }
        });
        jMenu3.add(MI_sair);

        jMenuBar2.add(jMenu3);

        Menu_Pacientes.setText("Pacientes");
        Menu_Pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_PacientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu_PacientesMousePressed(evt);
            }
        });
        Menu_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PacientesActionPerformed(evt);
            }
        });
        jMenuBar2.add(Menu_Pacientes);

        Menu_medicos.setText("Médicos");
        Menu_medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu_medicosMousePressed(evt);
            }
        });
        jMenuBar2.add(Menu_medicos);

        MC.setText("Consultas");
        MC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MCMousePressed(evt);
            }
        });
        jMenuBar2.add(MC);

        MConf.setText("Configurar");
        MConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MConfMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MConfMousePressed(evt);
            }
        });
        MConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MConfActionPerformed(evt);
            }
        });
        jMenuBar2.add(MConf);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PacientesActionPerformed

    }//GEN-LAST:event_Menu_PacientesActionPerformed

    private void MConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MConfActionPerformed

    }//GEN-LAST:event_MConfActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void MConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MConfMouseClicked
        
    }//GEN-LAST:event_MConfMouseClicked

    private void Menu_PacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_PacientesMouseClicked
        
    }//GEN-LAST:event_Menu_PacientesMouseClicked

    private void Menu_PacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_PacientesMousePressed
        JFrame Janela_pacientes = new Pacientes();
        Janela_pacientes.setLocationRelativeTo(null); //Centraliza a Janela
        Janela_pacientes.setVisible(true);
    }//GEN-LAST:event_Menu_PacientesMousePressed

    private void MConfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MConfMousePressed
        JFrame Janela_acesso = new Acesso();
        Janela_acesso.setLocationRelativeTo(null); //Centraliza a Janela
        Janela_acesso.setVisible(true);
    }//GEN-LAST:event_MConfMousePressed

    private void Menu_medicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_medicosMousePressed
        JFrame Janela_medicos = new Medicos();
        Janela_medicos.setLocationRelativeTo(null); //Centraliza a Janela
        Janela_medicos.setVisible(true);
    }//GEN-LAST:event_Menu_medicosMousePressed

    private void MCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCMousePressed
        JFrame Janela_consultas = new Consultas();
        Janela_consultas.setLocationRelativeTo(null); //Centraliza a Janela
        Janela_consultas.setVisible(true);
    }//GEN-LAST:event_MCMousePressed

    private void MI_sairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MI_sairMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MI_sairMouseReleased

    private void MI_sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MI_sairMousePressed
        dispose();
    }//GEN-LAST:event_MI_sairMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MC;
    private javax.swing.JMenu MConf;
    private javax.swing.JMenuItem MI_sair;
    private javax.swing.JMenu Menu_Pacientes;
    private javax.swing.JMenu Menu_medicos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
