/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


import Classes.Medico;
import DAO.ErpDAOException;
import DAO.MedicoDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yugurimaru
 */
public class Medicos_procurar extends javax.swing.JFrame {

    ArrayList<Medico> medico_arraylist = new ArrayList();
    
    /**
     * Creates new form Pacientes_procurar
     */
    public Medicos_procurar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF_nome = new javax.swing.JTextField();
        TF_telefone = new javax.swing.JTextField();
        RB_masculino = new javax.swing.JRadioButton();
        RB_feminino = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        TF_especialidade = new javax.swing.JTextField();
        DC_data_nascimento = new datechooser.beans.DateChooserPanel();
        CB_procurar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Medico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Selecione o Médico:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Data de Nascimento:");

        TF_nome.setEditable(false);

        TF_telefone.setEditable(false);

        buttonGroup1.add(RB_masculino);
        RB_masculino.setText("Masculino");

        buttonGroup1.add(RB_feminino);
        RB_feminino.setText("Feminino");

        jLabel6.setText("Especialidade:");

        TF_especialidade.setEditable(false);

        DC_data_nascimento.setLocked(true);

        CB_procurar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_procurarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 177, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel5))
                            .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_telefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_especialidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(RB_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_feminino))
                            .addComponent(CB_procurar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(CB_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RB_masculino)
                    .addComponent(RB_feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        MedicoDAO MDAO = new MedicoDAO();
        try {
            CB_procurar.removeAllItems();
            medico_arraylist = MDAO.Listar();

        } catch (Exception e) {
            System.out.println("problema");
        }

        for (int i = 0; i < medico_arraylist.size(); i++) {
            CB_procurar.addItem(medico_arraylist.get(i).getNome_med());
        }
        
        RB_masculino.setEnabled(false);
        RB_feminino.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void CB_procurarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_procurarItemStateChanged
        MedicoDAO MDAO = new MedicoDAO();

        try {

            Medico medico_selecionado = medico_arraylist.get(CB_procurar.getSelectedIndex());
            String id_paciente = String.valueOf(medico_selecionado.getID_Medico());
            int id_paciente_int = Integer.parseInt(id_paciente);

            Medico medico = MDAO.Procurar(id_paciente_int);

            if (medico != null) { // Verifica se o medico foi encontrado
                TF_nome.setText(medico.getNome_med());
                TF_especialidade.setText(medico.getEspecialidade());
                TF_telefone.setText(medico.getFone());

                Calendar calendar = Calendar.getInstance();
                calendar.setTime(medico.getData_nasc());
                DC_data_nascimento.setSelectedDate(calendar);

                if (medico.getSexo() == 'M' || medico.getSexo() == 'm') {
                    RB_masculino.setSelected(true);
                    RB_feminino.setSelected(false);
                } else {
                    RB_masculino.setSelected(false);
                    RB_feminino.setSelected(true);
                }
            } else {

                JOptionPane.showMessageDialog(rootPane, "Medico não encontrado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Entrada inválida. Certifique-se de que seja um número inteiro.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Problema ao procurar Medico");
        }
    }//GEN-LAST:event_CB_procurarItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_procurar;
    private datechooser.beans.DateChooserPanel DC_data_nascimento;
    private javax.swing.JRadioButton RB_feminino;
    private javax.swing.JRadioButton RB_masculino;
    private javax.swing.JTextField TF_especialidade;
    private javax.swing.JTextField TF_nome;
    private javax.swing.JTextField TF_telefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
