/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Medico;
import DAO.ErpDAOException;
import DAO.MedicoDAO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author yugurimaru
 */
public class Medicos_inserir extends javax.swing.JFrame {

    /**
     * Creates new form Pacientes_Inserir
     */
    public Medicos_inserir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF_nome = new javax.swing.JTextField();
        TF_telefone = new javax.swing.JTextField();
        BT_Salvar = new javax.swing.JButton();
        BT_Cancelar = new javax.swing.JButton();
        RB_masculino = new javax.swing.JRadioButton();
        RB_feminino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        TF_especialidade = new javax.swing.JTextField();
        DC_data_nascimento = new datechooser.beans.DateChooserPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Medicos");

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Data de nascimento:");

        TF_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_nomeActionPerformed(evt);
            }
        });

        TF_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_telefoneActionPerformed(evt);
            }
        });

        BT_Salvar.setText("Salvar");
        BT_Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BT_SalvarMousePressed(evt);
            }
        });

        BT_Cancelar.setText("Cancelar");
        BT_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_masculino);
        RB_masculino.setText("Masculino");

        buttonGroup1.add(RB_feminino);
        RB_feminino.setText("Feminino");

        jLabel5.setText("Especialidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_nome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_especialidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RB_masculino)
                                .addGap(18, 18, 18)
                                .addComponent(RB_feminino))
                            .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(BT_Cancelar)
                        .addGap(36, 36, 36)
                        .addComponent(BT_Salvar)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RB_masculino)
                    .addComponent(RB_feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Salvar)
                    .addComponent(BT_Cancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_nomeActionPerformed

    private void TF_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_telefoneActionPerformed

    private void BT_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_CancelarActionPerformed

    private void BT_SalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_SalvarMousePressed
        Medico M = new Medico();
        String nome, telefone, especialidade, data_string;
        Date dataNasc = null;
        char sexo = ' ';
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");
        
        if (TF_nome.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "É necessário o Nome");
        } else if ((RB_masculino.isSelected() == false) && (RB_feminino.isSelected() == false)) {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Sexo");
        } else {

            nome = TF_nome.getText();
            especialidade = TF_especialidade.getText();
            if (RB_feminino.isSelected() == true) {
                sexo = 'F';
            }
            if (RB_masculino.isSelected() == true) {
                sexo = 'M';
            }
            telefone = TF_telefone.getText();
            
            Calendar date = DC_data_nascimento.getSelectedDate();
            int mes = (int) date.get(Calendar.MONTH);
            mes += 1;
            data_string = (date.get(Calendar.DAY_OF_MONTH) + "/" + mes + "/" + date.get(Calendar.YEAR));
            if (data_string.equals("")) {
                dataNasc = null;
                
            } else {
                try {
                    dataNasc = dtOutput.parse(data_string);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro na conversão da data");
                }
            }
            M.setNome_med(nome);
            M.setData_nasc(dataNasc);
            M.setSexo(sexo);
            M.setFone(telefone);
            M.setEspecialidade(especialidade);
            
            try {
                MedicoDAO MDAO = new MedicoDAO();
                MDAO.Inserir(M);
                JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "problema na inserção do Medico");
            }
            dispose();
            
        }
    }//GEN-LAST:event_BT_SalvarMousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_Salvar;
    private datechooser.beans.DateChooserPanel DC_data_nascimento;
    private javax.swing.JRadioButton RB_feminino;
    private javax.swing.JRadioButton RB_masculino;
    private javax.swing.JTextField TF_especialidade;
    private javax.swing.JTextField TF_nome;
    private javax.swing.JTextField TF_telefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
