/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Paciente;
import DAO.ErpDAOException;
import DAO.PacienteDAO;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yugurimaru
 */
public class Pacientes_procurar extends javax.swing.JFrame {

    ArrayList<Paciente> paciente_arraylist = new ArrayList();

    /**
     * Creates new form Pacientes_procurar
     */
    public Pacientes_procurar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF_nome = new javax.swing.JTextField();
        TF_telefone = new javax.swing.JTextField();
        RB_masculino = new javax.swing.JRadioButton();
        RB_feminino = new javax.swing.JRadioButton();
        DC_data_nascimento = new datechooser.beans.DateChooserPanel();
        CB_procurar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Paciente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Selecione o paciente:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Data de Nascimento:");

        TF_nome.setEditable(false);

        TF_telefone.setEditable(false);

        buttonGroup1.add(RB_masculino);
        RB_masculino.setText("Masculino");

        buttonGroup1.add(RB_feminino);
        RB_feminino.setText("Feminino");

        DC_data_nascimento.setLocked(true);

        CB_procurar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_procurarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(RB_masculino)
                                .addGap(18, 18, 18)
                                .addComponent(RB_feminino))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_nome)
                                    .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CB_procurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RB_masculino)
                    .addComponent(RB_feminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DC_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PacienteDAO PDAO = new PacienteDAO();
        try {
            CB_procurar.removeAllItems();
            paciente_arraylist = PDAO.Listar();

        } catch (Exception e) {
            System.out.println("problema");
        }

        for (int i = 0; i < paciente_arraylist.size(); i++) {
            CB_procurar.addItem(paciente_arraylist.get(i).getNome_pac());
        }

        RB_masculino.setEnabled(false);
        RB_feminino.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void CB_procurarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_procurarItemStateChanged
        PacienteDAO PDAO = new PacienteDAO();

        try {

            Paciente paciente_selecionado = paciente_arraylist.get(CB_procurar.getSelectedIndex());
            String id_paciente = String.valueOf(paciente_selecionado.getCodigo());
            int id_paciente_int = Integer.parseInt(id_paciente);

            Paciente paciente = PDAO.procurar(id_paciente_int);

            if (paciente != null) {
                TF_nome.setText(paciente.getNome_pac());
                TF_telefone.setText(paciente.getFone());

                Calendar calendar = Calendar.getInstance();
                calendar.setTime(paciente.getData_pac());
                DC_data_nascimento.setSelectedDate(calendar);

                if (paciente.getSexo() == 'M' || paciente.getSexo() == 'm') {
                    RB_masculino.setSelected(true);
                    RB_feminino.setSelected(false);
                } else {
                    RB_masculino.setSelected(false);
                    RB_feminino.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Paciente não encontrado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Entrada inválida. Certifique-se de que seja um número inteiro.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Problema ao procurar Paciente");
        }
    }//GEN-LAST:event_CB_procurarItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_procurar;
    private datechooser.beans.DateChooserPanel DC_data_nascimento;
    private javax.swing.JRadioButton RB_feminino;
    private javax.swing.JRadioButton RB_masculino;
    private javax.swing.JTextField TF_nome;
    private javax.swing.JTextField TF_telefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
